version: "3.1"

language: en

pipeline:
- name: WhitespaceTokenizer
- name: RegexEntityExtractor
  use_regex_feature: true
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 100
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.1

policies:
- name: MemoizationPolicy
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: true
- name: UnexpecTEDIntentPolicy
  max_history: 5
  epochs: 100
assistant_id: 20250604-135727-level-booster
